### ISSUE TITLE
[Major] UX issue

### ISSUE THREAD

**Issue by 3ickey** [CourseVisor/CourseVisor#54]
**Describe the bug**
The app is really hard to use on mobile. Most UI elements are not responsive.   

**To Reproduce**
1. Go to 'Log in and enter details to log in'
2. Click on 'Submit a new review" Enter details and submit
3. See error where most UI elements are not responsive making it hard to use

**Expected behavior**
If the mission is learning through student-centered information I expect a fully responsive app on mobile because I think that's what most students use on a daily basis 

**Screenshots**
<img width="380" alt="Screen Shot 2019-12-09 at 12 04 53 PM" src="https://user-images.githubusercontent.com/32441472/70469509-0462b280-1a7e-11ea-8242-7426cbe31ec9.png">

**Smartphone:**
 - Device: iPhone 7 Plus
 - OS: IOS 13.1.2
 - Browser: Safari

**Comment by albertli354** [comment]
Thanks for your feedback. We acknowledge the need for a mobile-based website for students.  A fully responsive app on a cell phone requires a redesign and reengineering to the current website, which is impossible given the current timeframe. In order to make the website fully responsive, we need to use frameworks like bootstrap, which means we need to abandon our current CSS framework and program the website from the start. After careful consideration of implementing such a feature, we decided it is impossible for the team to do so before the deadline.
